#!/usr/bin/env python3

# =============================================================================
# merge_maf.py
# =============================================================================
#
# DESCRIPTION:
#   Merges one or more MAF (Mutation Annotation Format) files from a directory
#   into a single unified output table. The script produces three output files
#   targeting different audiences and use cases.
#
#   OUTPUT FILES:
#
#     - Final_result_tier1.maf
#         A standard MAF file containing all fields except those marked as
#         "drop" in the YAML config. No metadata second header row. Intended
#         as a clean, tool-compatible MAF file for downstream analysis.
#
#     - Final_result_tier2.tsv
#         A tab-separated file for bioinformaticians. Contains Tier 2 fields
#         as defined in Config.yaml (generated by build_config.py). Includes
#         a two-row header: field names on row 1, metadata (description,
#         source, version) on row 2.
#
#     - Final_result_tier3.tsv
#         A tab-separated file for clinical scientists. Contains Tier 3 fields
#         as defined in Config.yaml (generated by build_config.py). Includes
#         a two-row header: field names on row 1, metadata on row 2.
#         To change which fields appear here, update TIER3_FIELDS in
#         build_config.py and re-run it to regenerate Config.yaml.
#
#   Fields marked as "drop" in the YAML config are treated as redundant or
#   duplicate fields and are excluded from ALL output files without exception.
#
# INPUT:
#   - A directory containing one or more MAF files (.maf)
#   - A YAML configuration file (Config.yaml) generated by build_config.py,
#     which defines per-field metadata (description, source, version, tier)
#     and wildcard patterns for dynamically generated field groups such as
#     ONCOKB_DIAG_* and ONCOKB_TX_*
#
# OUTPUT:
#   - Final_result_tier1.maf   : all non-drop fields, single header, MAF format
#   - Final_result_tier2.tsv   : Tier 2 fields, two-row header
#   - Final_result_tier3.tsv   : Tier 3 fields, two-row header
#
# PROCESSING STEPS:
#   1.  Standardize FORMAT_DATA column name across all input files
#   2.  Expand FORMAT genotype fields (GT, AD, VAF, etc.) into separate columns
#   3.  Expand structured annotation columns (e.g. CIViC_CSQ) using pipe-
#       delimited subfield definitions from the YAML config
#   4.  Calculate End_Position based on variant type (SNV, indel, SV)
#   5.  Clean field values (replace empty arrays, URL-encoded characters, etc.)
#   6.  Compute VAF from allelic depth (AD) if not already present
#   7.  Drop any columns listed in COLS_TO_REMOVE
#   8.  Report columns not documented in the YAML config (warnings only)
#   9.  Remove all columns marked as "drop" in the YAML config
#   10. Write Tier 1 MAF file (single header, all remaining columns)
#   11. Split columns by tier (read from Config.yaml) and build two-row headers
#   12. Write Tier 2 and Tier 3 TSV files
#
# TIER DEFINITIONS (controlled by build_config.py, not this script):
#   Tier 1 : All non-drop fields — written to Final_result_tier1.maf
#   Tier 2 : ~400 bioinformatician fields — written to Final_result_tier2.tsv
#   Tier 3 : ~200 clinician fields — written to Final_result_tier3.tsv
#   Drop   : Excluded from all outputs
#
#   To change tier assignments, edit TIER2_FIELDS, TIER3_FIELDS, or DROP_FIELDS
#   in build_config.py and re-run it to regenerate Config.yaml.
#
# USAGE:
#   python merge_maf.py
#
#   Edit the entry point at the bottom of the script to configure:
#     - input_dir  : directory containing input MAF files
#     - output_dir : directory where output files will be written
#     - yaml_config: path to the generated Config.yaml file
#
# DEPENDENCIES:
#   - Python 3.8+
#   - pandas
#   - pyyaml
#
# RELATED FILES:
#   - ConfigORIGINAL.yaml : human-maintained field metadata template
#   - Config.yaml         : generated config consumed by this script
#   - build_config.py     : script that generates Config.yaml from the template
#
# AUTHOR:
#   Variant annotation pipeline — Manuel
# =============================================================================

import os
import fnmatch
import ast
import json
import yaml
import pandas as pd
import argparse


COLS_TO_REMOVE = []


# === Load YAML config ===
def load_field_config(yaml_path):
    """
    Load field metadata and pattern definitions from a YAML configuration file.

    Reads the Config.yaml file generated by build_config.py and extracts:
      - Explicit field definitions (description, source, version, tier)
      - Pattern-based field definitions for dynamically generated columns

    Parameters
    ----------
    yaml_path : str
        Path to the YAML configuration file.

    Returns
    -------
    tuple
        (fields, patterns) where:
        - fields: dict of field metadata
        - patterns: list of wildcard pattern definitions

    Raises
    ------
    ValueError
        If the YAML file does not contain a 'fields' section.
    """

    with open(yaml_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    if not config or "fields" not in config:
        raise ValueError(f"YAML file '{yaml_path}' does not contain a top-level 'fields' section.")

    fields = config["fields"]
    patterns = config.get("field_patterns", [])

    return fields, patterns


# === Resolve field metadata with pattern fallback ===
def resolve_field_meta(col, field_config, field_patterns):
    """
    Resolve metadata for a given column using exact match or pattern matching.

    Attempts to retrieve metadata (description, source, version, tier) for a column:
      1. First checks for an exact match in the field configuration
      2. Falls back to wildcard pattern matching if no exact match is found

    Parameters
    ----------
    col : str
        Column name.
    field_config : dict
        Dictionary of explicitly defined fields.
    field_patterns : list
        List of pattern-based field definitions.

    Returns
    -------
    dict
        Metadata dictionary for the column, or empty dict if not found.
    """

    # Try exact match first
    if col in field_config:
        return field_config[col]

    # Fall back to wildcard pattern matching
    for pattern_def in field_patterns:
        pattern = pattern_def.get("pattern", "")
        if fnmatch.fnmatch(col, pattern):
            return {k: v for k, v in pattern_def.items() if k != "pattern"}

    return {}


# === Step 1: Standardize FORMAT_DATA column per file ===
def standardize_format_column(df):
    """
    Standardize FORMAT sample column naming across input MAF files.

    Renames the column immediately following the 'FORMAT' column to 'FORMAT_DATA'
    to ensure consistency across different input files.

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.

    Returns
    -------
    pandas.DataFrame
        Dataframe with standardized FORMAT_DATA column.
    """

    if "FORMAT" not in df.columns:
        return df

    format_idx = df.columns.get_loc("FORMAT")

    if format_idx + 1 < len(df.columns):
        sample_col = df.columns[format_idx + 1]
        df = df.rename(columns={sample_col: "FORMAT_DATA"})

    return df


# === Step 2: Expand FORMAT fields ===
def normalize_format_fields(df):
    """
    Expand FORMAT genotype fields into individual columns.

    Parses the 'FORMAT' and 'FORMAT_DATA' columns and splits genotype values
    (e.g. GT, AD, VAF) into separate columns for easier downstream analysis.

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.

    Returns
    -------
    pandas.DataFrame
        Dataframe with expanded genotype fields.
    """

    if "FORMAT" not in df.columns or "FORMAT_DATA" not in df.columns:
        return df

    def parse_format(row):

        format_str = str(row.get("FORMAT", "") or "")
        data_str = str(row.get("FORMAT_DATA", "") or "")

        keys = format_str.split(":")
        values = data_str.split(":")

        if len(values) < len(keys):
            values += [None] * (len(keys) - len(values))

        return dict(zip(keys, values))

    parsed_rows = df.apply(parse_format, axis=1)

    all_keys = set()

    for d in parsed_rows:
        all_keys.update(d.keys())

    for key in sorted(all_keys):

        if key in df.columns:
            continue

        df[key] = parsed_rows.apply(lambda d: d.get(key, None))

    return df


# === Step 2.5: Expand structured annotation columns (e.g CIViC_CSQ) ===
def expand_structured_columns(df, field_config):
    """
    Expand structured annotation fields into multiple columns.

    Splits annotation fields (e.g. CIViC_CSQ) into subfields based on the
    pipe-delimited description defined in the YAML configuration.

    Handles both:
      - VEP-style annotations (comma-separated records)
      - CIViC-style annotations (ampersand-separated records)

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.
    field_config : dict
        Field metadata configuration.

    Returns
    -------
    pandas.DataFrame
        Dataframe with expanded annotation columns.
    """

    for field, meta in field_config.items():

        if field not in df.columns:
            continue

        description = meta.get("description", "")

        if "|" not in description:
            continue

        # Avoid splitting natural language descriptions
        tokens = description.split("|")

        if any(len(t.strip()) > 40 for t in tokens):
            continue

        subfields = [x.strip() for x in description.split("|")]
        n_fields = len(subfields)
        def split_first_record(value):

            if pd.isna(value):
                return [None] * n_fields

            value = str(value)

            # CASE 1 — VEP style (records separated by comma)
            if "," in value:
                first_record = value.split(",")[0]
                parts = first_record.split("&")

            # CASE 2 — CIViC style (records concatenated with &)
            else:
                parts_all = value.split("&")

                if len(parts_all) % n_fields != 0:
                    print("WARNING: CIViC field structure mismatch detected in dataset")

                records = [
                    parts_all[i:i+n_fields]
                    for i in range(0, len(parts_all), n_fields)
                ]

                parts = records[0]

            if len(parts) < n_fields:
                parts += [None] * (n_fields - len(parts))

            parts = parts[:n_fields]
            return parts

        expanded = df[field].apply(split_first_record).apply(pd.Series)

        expanded.columns = [f"{field}_{c}" for c in subfields]

        df = df.drop(columns=[field])
        df = pd.concat([df, expanded], axis=1)

    return df


# === Step 2.6: Expand OncoKB JSON array columns ===
# ONCOKB_treatments        → ONCOKB_TX_{index}_{field}
# ONCOKB_diagnosticImpl... → ONCOKB_DIAG_{index}_{field}
# ONCOKB_prognosticImpl... → ONCOKB_PROG_{index}_{field}

_ONCOKB_JSON_FIELDS = {
    "ONCOKB_treatments":              "ONCOKB_TX",
    "ONCOKB_diagnosticImplications":  "ONCOKB_DIAG",
    "ONCOKB_prognosticImplications":  "ONCOKB_PROG",
}


def _flatten_entry(entry, prefix=""):
    """Recursively flatten a dict to dotted key names, serialising lists."""
    out = {}
    for k, v in entry.items():
        full_key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.update(_flatten_entry(v, full_key))
        elif isinstance(v, list):
            # Lists of dicts (e.g. drugs): join their primary string value
            parts = []
            for item in v:
                if isinstance(item, dict):
                    # prefer drugName, then name, then first value
                    parts.append(str(item.get("drugName") or item.get("name") or next(iter(item.values()), "")))
                else:
                    parts.append(str(item))
            out[full_key] = ",".join(parts)
        else:
            out[full_key] = "" if v is None else str(v)
    return out


def expand_oncokb_json_arrays(df):
    """
    Expand ONCOKB JSON array columns into per-entry flat columns.

    For each row, parses the JSON array and emits columns named
    {PREFIX}_{index}_{field} — e.g. ONCOKB_TX_0_level, ONCOKB_TX_0_drugs.
    The number of index columns is determined by the maximum array length
    across all rows in the dataframe.
    """
    for src_col, col_prefix in _ONCOKB_JSON_FIELDS.items():
        if src_col not in df.columns:
            continue

        # --- Parse each row's JSON array ---
        parsed = []
        max_entries = 0
        for val in df[src_col]:
            try:
                entries = json.loads(val) if val and val != "[]" else []
            except (json.JSONDecodeError, TypeError):
                entries = []
            parsed.append(entries)
            max_entries = max(max_entries, len(entries))

        if max_entries == 0:
            print(f"  {src_col}: all rows empty — skipping expansion")
            continue

        print(f"  {src_col}: expanding {max_entries} entries → prefix {col_prefix}")

        # --- Collect all field names across all entries ---
        all_fields = []
        seen = set()
        for row_entries in parsed:
            for entry in row_entries:
                for k in _flatten_entry(entry).keys():
                    if k not in seen:
                        all_fields.append(k)
                        seen.add(k)

        # --- Build new columns ---
        new_cols = {}
        for i in range(max_entries):
            for field in all_fields:
                col_name = f"{col_prefix}_{i}_{field}"
                new_cols[col_name] = []

        for row_entries in parsed:
            for i in range(max_entries):
                if i < len(row_entries):
                    flat = _flatten_entry(row_entries[i])
                else:
                    flat = {}
                for field in all_fields:
                    col_name = f"{col_prefix}_{i}_{field}"
                    new_cols[col_name].append(flat.get(field, ""))

        new_df = pd.DataFrame(new_cols, index=df.index)
        df = df.drop(columns=[src_col])
        df = pd.concat([df, new_df], axis=1)

    return df


# === Step 3: Calculate End_Position ===
def calculate_end_position(df):
    """
    Compute End_Position for variants based on variant type.

    Determines the genomic end position using:
      - REF/ALT length for SNVs and indels
      - Structural variant annotations (Manta INS, DUP, BND)

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.

    Returns
    -------
    pandas.DataFrame
        Dataframe with 'End_Position' column added.
    """

    def compute_end(row):

        id_val = row.get("ID", "")
        ref = row.get("REF", "") or ""
        alt = row.get("ALT", "") or ""
        dupsvlen = row.get("DUPSVLEN", "")

        try:
            start = int(row["Start_Position"])
        except (ValueError, TypeError, KeyError):
            return None

        if id_val == ".":
            if len(ref) == len(alt):
                return start
            return start + max(len(ref), len(alt)) - 1

        if str(id_val).startswith("MantaBND"):
            return None

        if str(id_val).startswith("MantaINS"):
            if alt == "<INS>":
                try:
                    return start + int(dupsvlen)
                except (ValueError, TypeError):
                    return None
            return start + len(alt)

        if str(id_val).startswith("MantaDUP"):
            try:
                return start + int(dupsvlen)
            except (ValueError, TypeError):
                return None

        return None

    df["End_Position"] = df.apply(compute_end, axis=1)

    return df


# === Step 4: Clean values ===
def clean_column_values(df):
    """
    Clean and normalize column values.

    Performs:
      - Replacement of placeholder values (e.g. '[]', URL-encoded characters)
      - Normalization of HGVSc field (removal of transcript prefix)

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.

    Returns
    -------
    pandas.DataFrame
        Cleaned dataframe.
    """

    df = df.replace({"[]": "", "%3D": "="}, regex=False).infer_objects(copy=False)

    if "HGVSc" in df.columns:
        df["HGVSc"] = (
            df["HGVSc"]
            .astype(str)
            .apply(lambda x: x.split(":", 1)[1] if ":" in x else x)
        )

    return df


# === Step 5: Compute VAF ===
def add_vaf_column(df, ad_column="AD"):
    """
    Compute Variant Allele Frequency (VAF) from allelic depth.

    Calculates VAF using:
        VAF = ALT / (REF + ALT)

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.
    ad_column : str, optional
        Column containing allelic depth (default is 'AD').

    Returns
    -------
    pandas.DataFrame
        Dataframe with 'VAF' column added.
    """

    if ad_column not in df.columns:
        return df

    def compute_vaf(value):

        try:
            ref, alt = str(value).split(",")
            ref = float(ref)
            alt = float(alt)
            total = ref + alt
            return alt / total if total > 0 else 0
        except Exception:
            return None

    df["VAF"] = df[ad_column].apply(compute_vaf)

    return df


# === Step 6: Drop columns ===
def drop_columns(df, cols_to_remove):
    """
    Remove unwanted columns from the dataframe.

    Drops columns specified in COLS_TO_REMOVE while ignoring missing columns.

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.
    cols_to_remove : list
        List of column names to remove.

    Returns
    -------
    pandas.DataFrame
        Dataframe with selected columns removed.
    """

    return df.drop(columns=cols_to_remove, errors="ignore")


# === Step 7: Report undocumented columns ===
def report_undocumented_columns(df, field_config, field_patterns):
    """
    Identify and report columns not defined in the YAML configuration.

    Checks all columns against:
      - Explicit field definitions
      - Pattern-based definitions

    Prints a warning listing any undocumented columns.

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe.
    field_config : dict
        Field metadata configuration.
    field_patterns : list
        Pattern-based field definitions.

    Returns
    -------
    None
    Columns are not missed but they the second header will not tell you description and version
    """

    undocumented = []

    for col in sorted(df.columns):
        meta = resolve_field_meta(col, field_config, field_patterns)
        if not meta:
            undocumented.append(col)

    if undocumented:
        print("\n=== WARNING: Undocumented columns found ===")
        for col in undocumented:
            print(f"Undocumented column: {col}")


# === Step 8: Build two-row header ===
def build_multiindex_header(df, field_config, field_patterns):

    metadata_row = []

    for col in df.columns:

        meta = resolve_field_meta(col, field_config, field_patterns)

        description = meta.get("description", "UNKNOWN")
        source      = meta.get("source", "UNKNOWN")
        version     = meta.get("version", "UNKNOWN")

        metadata_row.append(f"{description} | {source} | {version}")

    df.columns = pd.MultiIndex.from_arrays(
        [df.columns, metadata_row],
        names=["Field", "Metadata"]
    )

    return df


# === Step 9: Split dataframe by tier ===
# Tier assignments are read from Config.yaml (set by build_config.py).
# Tier 2 columns : fields with tier == 2 in the YAML
# Tier 3 columns : fields with tier == 3 in the YAML
# All other non-drop columns default to Tier 1 (present in the MAF only)
def split_by_tier(df, field_config, field_patterns):

    tier2_cols = []
    tier3_cols = []
    drop_cols  = []

    for col in df.columns:

        meta = resolve_field_meta(col, field_config, field_patterns)
        tier = meta.get("tier")

        if tier == "drop":
            drop_cols.append(col)

        elif tier == 2:
            tier2_cols.append(col)

        elif tier == 3:
            tier3_cols.append(col)
            tier2_cols.append(col)

        # tier == 1 or unassigned: present in MAF only, not in TSV outputs

    print(f"\nTier2 columns: {len(tier2_cols)}")
    print(f"Tier3 columns: {len(tier3_cols)}")

    return df[tier2_cols], df[tier3_cols]


# === Main merge function ===
def merge_maf_files(input_dir, output_dir, yaml_config):

    field_config, field_patterns = load_field_config(yaml_config)

    maf_files = [f for f in os.listdir(input_dir) if f.lower().endswith(".maf")]

    if not maf_files:
        raise ValueError("No MAF files found in the directory.")

    dfs = []

    for maf in maf_files:

        path = os.path.join(input_dir, maf)

        print(f"Reading: {path}")

        df = pd.read_csv(path, sep="\t", dtype=str)

        df = standardize_format_column(df)

        dfs.append(df)

    merged = pd.concat(dfs, axis=0, ignore_index=True, sort=False)

    merged = calculate_end_position(merged)
    merged = normalize_format_fields(merged)
    merged = expand_structured_columns(merged, field_config)
    print("\n=== Expanding OncoKB JSON array columns ===")
    merged = expand_oncokb_json_arrays(merged)
    merged = clean_column_values(merged)
    merged = add_vaf_column(merged)
    # NOTE: drop_columns(merged, COLS_TO_REMOVE) is intentionally deferred until
    # AFTER the CNA fixes below, because source columns such as ONCOKB_treatments,
    # ONCOKB_FDA_LVL, ONCOKB_SENS_LVL are tier=drop and must still be present
    # when we populate LEVEL_* and HIGHEST_*_LEVEL for CNA rows.

    # Bug fix 1: ONCOKB_highestFdaLevel is empty because MafAnnotator
    # does not populate it for UNKNOWN tumor type. Fill from ONCOKB_FDA_LVL
    # which was written by oncokb2.0.py directly from the API response.
    # --------------------------------------------------------
    if "ONCOKB_highestFdaLevel" in merged.columns and "ONCOKB_FDA_LVL" in merged.columns:
        mask = merged["ONCOKB_highestFdaLevel"].fillna("").eq("")
        merged.loc[mask, "ONCOKB_highestFdaLevel"] = merged.loc[mask, "ONCOKB_FDA_LVL"].fillna("")
        filled = mask.sum()
        if filled:
            print(f"\nFilled {filled} empty ONCOKB_highestFdaLevel values from ONCOKB_FDA_LVL")

    # --------------------------------------------------------
    # Bug fix 2: MafAnnotator cannot handle CNA rows — it sets
    # VARIANT_IN_ONCOKB=False, ONCOGENIC=Unknown, MUTATION_EFFECT=Unknown
    # for all CNAs even when oncokb2.0.py got correct values.
    # For CNA rows, overwrite those three columns from the oncokb2.0.py
    # source columns (ONCOKB_variantExist, ONCOKB_oncogenic,
    # ONCOKB_mutationEffect.knownEffect, ONCOKB_mutationEffect.citations.pmids).
    # --------------------------------------------------------
    cna_mask = merged.get("ONCOKB_QUERY_TYPE", pd.Series("", index=merged.index)).fillna("").eq("CNA")
    if cna_mask.any():
        if "VARIANT_IN_ONCOKB" in merged.columns and "ONCOKB_variantExist" in merged.columns:
            merged.loc[cna_mask, "VARIANT_IN_ONCOKB"] = merged.loc[cna_mask, "ONCOKB_variantExist"].fillna("")
        if "ONCOGENIC" in merged.columns and "ONCOKB_oncogenic" in merged.columns:
            merged.loc[cna_mask, "ONCOGENIC"] = merged.loc[cna_mask, "ONCOKB_oncogenic"].fillna("")
        if "MUTATION_EFFECT" in merged.columns and "ONCOKB_mutationEffect.knownEffect" in merged.columns:
            merged.loc[cna_mask, "MUTATION_EFFECT"] = merged.loc[cna_mask, "ONCOKB_mutationEffect.knownEffect"].fillna("")
        if "MUTATION_EFFECT_CITATIONS" in merged.columns and "ONCOKB_mutationEffect.citations.pmids" in merged.columns:
            # oncokb2.0.py stores as Python list repr; normalise to semicolon-separated PMIDs
            def _norm_pmids(v):
                v = str(v).strip()
                if not v or v in ("[]", "nan", ""):
                    return ""
                # strip brackets and quotes, split on comma
                v = v.strip("[]").replace("'", "").replace('"', "")
                return ";".join(p.strip() for p in v.split(",") if p.strip())
            merged.loc[cna_mask, "MUTATION_EFFECT_CITATIONS"] = (
                merged.loc[cna_mask, "ONCOKB_mutationEffect.citations.pmids"].fillna("").apply(_norm_pmids)
            )
        # ---- Treatment levels from ONCOKB_treatments JSON ----
        # MafAnnotator leaves LEVEL_1..LEVEL_R2, HIGHEST_SENSITIVE_LEVEL,
        # HIGHEST_RESISTANCE_LEVEL empty for CNAs. Populate from oncokb2.0.py JSON.
        if "ONCOKB_treatments" in merged.columns:
            _level_cols = ["LEVEL_1", "LEVEL_2", "LEVEL_3A", "LEVEL_3B",
                           "LEVEL_4", "LEVEL_R1", "LEVEL_R2"]

            def _extract_levels(treatments_json):
                treatments = []
                if treatments_json and treatments_json not in ("[]", "", "nan"):
                    try:
                        treatments = json.loads(treatments_json)
                    except (json.JSONDecodeError, TypeError):
                        try:
                            treatments = ast.literal_eval(treatments_json)
                        except Exception:
                            treatments = []
                out = {lc: [] for lc in _level_cols}
                for t in treatments:
                    lvl = t.get("level", "")
                    if lvl in out:
                        for d in t.get("drugs", []):
                            name = d.get("drugName", "")
                            if name and name not in out[lvl]:
                                out[lvl].append(name)
                return {k: ",".join(v) for k, v in out.items()}

            for cna_idx in merged.index[cna_mask]:
                tx_json = merged.at[cna_idx, "ONCOKB_treatments"]
                levels = _extract_levels(tx_json)
                for lc, val in levels.items():
                    if lc in merged.columns and val:
                        merged.at[cna_idx, lc] = val

        # ---- HIGHEST_SENSITIVE_LEVEL / HIGHEST_RESISTANCE_LEVEL from oncokb2.0.py ----
        if "HIGHEST_SENSITIVE_LEVEL" in merged.columns and "ONCOKB_SENS_LVL" in merged.columns:
            hs_empty = cna_mask & merged["HIGHEST_SENSITIVE_LEVEL"].fillna("").eq("")
            merged.loc[hs_empty, "HIGHEST_SENSITIVE_LEVEL"] = merged.loc[hs_empty, "ONCOKB_SENS_LVL"].fillna("")
        if "HIGHEST_RESISTANCE_LEVEL" in merged.columns and "ONCOKB_RESIST_LVL" in merged.columns:
            hr_empty = cna_mask & merged["HIGHEST_RESISTANCE_LEVEL"].fillna("").eq("")
            merged.loc[hr_empty, "HIGHEST_RESISTANCE_LEVEL"] = merged.loc[hr_empty, "ONCOKB_RESIST_LVL"].fillna("")

        n_cna = int(cna_mask.sum())
        print(f"\nApplied CNA overwrite fix for {n_cna} CNA rows "
              f"(VARIANT_IN_ONCOKB, ONCOGENIC, MUTATION_EFFECT, treatment levels, highest levels)")

    # Now safe to drop COLS_TO_REMOVE (source columns already consumed above)
    merged = drop_columns(merged, COLS_TO_REMOVE)

    report_undocumented_columns(merged, field_config, field_patterns)

    # --------------------------------------------------------
    # Remove all columns marked as "drop" in the YAML config.
    # These are redundant or duplicate fields and are excluded
    # from every output file without exception.
    # --------------------------------------------------------
    drop_cols = [
        col for col in merged.columns
        if resolve_field_meta(col, field_config, field_patterns).get("tier") == "drop"
    ]

    print(f"\nDropped columns (tier=drop): {len(drop_cols)}")
    if drop_cols:
        for c in drop_cols:
            print(f"  - {c}")

    merged = merged.drop(columns=drop_cols, errors="ignore")

    os.makedirs(output_dir, exist_ok=True)

    tier1_maf  = os.path.join(output_dir, "Final_result_tier1.maf")
    tier2_file = os.path.join(output_dir, "Final_result_tier2.tsv")
    tier3_file = os.path.join(output_dir, "Final_result_tier3.tsv")

    # --------------------------------------------------------
    # Tier 1 MAF: all remaining non-drop columns, single header.
    # Standard MAF format — no metadata second row.
    # --------------------------------------------------------
    print(f"\nTier1 columns: {len(merged.columns)}")
    print(f"Writing Tier1 MAF (all non-drop columns, no metadata header): {tier1_maf}")
    with open(tier1_maf, "w") as fh:
        fh.write("#version 2.4\n")
        merged.to_csv(fh, sep="\t", index=False)

    # --------------------------------------------------------
    # Split into Tier 2 and Tier 3 subsets.
    # Tier assignments come from Config.yaml — to change which
    # fields appear in each file, edit build_config.py and
    # re-run it to regenerate Config.yaml.
    # --------------------------------------------------------
    tier2_df, tier3_df = split_by_tier(merged, field_config, field_patterns)

    # --------------------------------------------------------
    # Tier 2 TSV: bioinformatician fields, two-row header.
    # --------------------------------------------------------
    tier2_df = build_multiindex_header(tier2_df, field_config, field_patterns)

    print(f"Writing Tier2 TSV (bioinformaticians, two-row header): {tier2_file}")
    tier2_df.to_csv(tier2_file, sep="\t", index=False)

    # --------------------------------------------------------
    # Tier 3 TSV: clinical scientist fields, two-row header.
    # --------------------------------------------------------
    if tier3_df.empty or len(tier3_df.columns) == 0:
        print("\nWARNING: No Tier 3 columns found in data.")
        print("To populate Final_result_tier3.tsv, add fields to TIER3_FIELDS")
        print("in build_config.py and re-run it to regenerate Config.yaml.")
    else:
        tier3_df = build_multiindex_header(tier3_df, field_config, field_patterns)
        print(f"Writing Tier3 TSV (clinical scientists, two-row header): {tier3_file}")
        tier3_df.to_csv(tier3_file, sep="\t", index=False)


# === Entry point ===
if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, help="Path to Config.yaml")
    args = parser.parse_args()

    merge_maf_files(
        input_dir="./FINAL_Table/",
        output_dir="./output/",
        yaml_config=args.config
    )