#!/usr/bin/env python3

# =============================================================================
# merge_maf.py
# =============================================================================
#
# DESCRIPTION:
#   Merges one or more MAF (Mutation Annotation Format) files from a directory
#   into a single unified output table. The script produces three output files
#   targeting different audiences and use cases.
#
#   OUTPUT FILES:
#
#     - Final_result_tier1.maf
#         A standard MAF file containing all fields except those marked as
#         "drop" in the YAML config. No metadata second header row. Intended
#         as a clean, tool-compatible MAF file for downstream analysis.
#
#     - Final_result_tier2.tsv
#         A tab-separated file for bioinformaticians. Contains Tier 2 fields
#         as defined in Config.yaml (generated by build_config.py). Includes
#         a two-row header: field names on row 1, metadata (description,
#         source, version) on row 2.
#
#     - Final_result_tier3.tsv
#         A tab-separated file for clinical scientists. Contains Tier 3 fields
#         as defined in Config.yaml (generated by build_config.py). Includes
#         a two-row header: field names on row 1, metadata on row 2.
#         To change which fields appear here, update TIER3_FIELDS in
#         build_config.py and re-run it to regenerate Config.yaml.
#
#   Fields marked as "drop" in the YAML config are treated as redundant or
#   duplicate fields and are excluded from ALL output files without exception.
#
# INPUT:
#   - A directory containing one or more MAF files (.maf)
#   - A YAML configuration file (Config.yaml) generated by build_config.py,
#     which defines per-field metadata (description, source, version, tier)
#     and wildcard patterns for dynamically generated field groups such as
#     ONCOKB_DIAG_* and ONCOKB_TX_*
#
# OUTPUT:
#   - Final_result_tier1.maf   : all non-drop fields, single header, MAF format
#   - Final_result_tier2.tsv   : Tier 2 fields, two-row header
#   - Final_result_tier3.tsv   : Tier 3 fields, two-row header
#
# PROCESSING STEPS:
#   1.  Standardize FORMAT_DATA column name across all input files
#   2.  Expand FORMAT genotype fields (GT, AD, VAF, etc.) into separate columns
#   3.  Expand structured annotation columns (e.g. CIViC_CSQ) using pipe-
#       delimited subfield definitions from the YAML config
#   4.  Calculate End_Position based on variant type (SNV, indel, SV)
#   5.  Clean field values (replace empty arrays, URL-encoded characters, etc.)
#   6.  Compute VAF from allelic depth (AD) if not already present
#   7.  Drop any columns listed in COLS_TO_REMOVE
#   8.  Report columns not documented in the YAML config (warnings only)
#   9.  Remove all columns marked as "drop" in the YAML config
#   10. Write Tier 1 MAF file (single header, all remaining columns)
#   11. Split columns by tier (read from Config.yaml) and build two-row headers
#   12. Write Tier 2 and Tier 3 TSV files
#
# TIER DEFINITIONS (controlled by build_config.py, not this script):
#   Tier 1 : All non-drop fields — written to Final_result_tier1.maf
#   Tier 2 : ~400 bioinformatician fields — written to Final_result_tier2.tsv
#   Tier 3 : ~200 clinician fields — written to Final_result_tier3.tsv
#   Drop   : Excluded from all outputs
#
#   To change tier assignments, edit TIER2_FIELDS, TIER3_FIELDS, or DROP_FIELDS
#   in build_config.py and re-run it to regenerate Config.yaml.
#
# USAGE:
#   python merge_maf.py
#
#   Edit the entry point at the bottom of the script to configure:
#     - input_dir  : directory containing input MAF files
#     - output_dir : directory where output files will be written
#     - yaml_config: path to the generated Config.yaml file
#
# DEPENDENCIES:
#   - Python 3.8+
#   - pandas
#   - pyyaml
#
# RELATED FILES:
#   - ConfigORIGINAL.yaml : human-maintained field metadata template
#   - Config.yaml         : generated config consumed by this script
#   - build_config.py     : script that generates Config.yaml from the template
#
# AUTHOR:
#   Variant annotation pipeline — Manuel
# =============================================================================

import os
import fnmatch
import yaml
import pandas as pd
import argparse


COLS_TO_REMOVE = []


# === Load YAML config ===
def load_field_config(yaml_path):

    with open(yaml_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    if not config or "fields" not in config:
        raise ValueError(f"YAML file '{yaml_path}' does not contain a top-level 'fields' section.")

    fields = config["fields"]
    patterns = config.get("field_patterns", [])

    return fields, patterns


# === Resolve field metadata with pattern fallback ===
def resolve_field_meta(col, field_config, field_patterns):

    # Try exact match first
    if col in field_config:
        return field_config[col]

    # Fall back to wildcard pattern matching
    for pattern_def in field_patterns:
        pattern = pattern_def.get("pattern", "")
        if fnmatch.fnmatch(col, pattern):
            return {k: v for k, v in pattern_def.items() if k != "pattern"}

    return {}


# === Step 1: Standardize FORMAT_DATA column per file ===
def standardize_format_column(df):

    if "FORMAT" not in df.columns:
        return df

    format_idx = df.columns.get_loc("FORMAT")

    if format_idx + 1 < len(df.columns):
        sample_col = df.columns[format_idx + 1]
        df = df.rename(columns={sample_col: "FORMAT_DATA"})

    return df


# === Step 2: Expand FORMAT fields ===
def normalize_format_fields(df):

    if "FORMAT" not in df.columns or "FORMAT_DATA" not in df.columns:
        return df

    def parse_format(row):

        format_str = str(row.get("FORMAT", "") or "")
        data_str = str(row.get("FORMAT_DATA", "") or "")

        keys = format_str.split(":")
        values = data_str.split(":")

        if len(values) < len(keys):
            values += [None] * (len(keys) - len(values))

        return dict(zip(keys, values))

    parsed_rows = df.apply(parse_format, axis=1)

    all_keys = set()

    for d in parsed_rows:
        all_keys.update(d.keys())

    for key in sorted(all_keys):

        if key in df.columns:
            continue

        df[key] = parsed_rows.apply(lambda d: d.get(key, None))

    return df


# === Step 2.5: Expand structured annotation columns (e.g CIViC_CSQ) ===
def expand_structured_columns(df, field_config):

    for field, meta in field_config.items():

        if field not in df.columns:
            continue

        description = meta.get("description", "")

        if "|" not in description:
            continue

        # Avoid splitting natural language descriptions
        tokens = description.split("|")

        if any(len(t.strip()) > 40 for t in tokens):
            continue

        subfields = [x.strip() for x in description.split("|")]
        n_fields = len(subfields)

        print("\n====================================================")
        print(f"Expanding structured column: {field}")
        print(f"Detected {n_fields} subfields")

        print("\nHeader structure:")
        for i, sf in enumerate(subfields):
            print(f"  {i:02d} -> {sf}")

        def split_first_record(value):

            if pd.isna(value):
                return [None] * n_fields

            value = str(value)

            # CASE 1 — VEP style (records separated by comma)
            if "," in value:
                first_record = value.split(",")[0]
                parts = first_record.split("&")

            # CASE 2 — CIViC style (records concatenated with &)
            else:
                parts_all = value.split("&")

                if len(parts_all) % n_fields != 0:
                    print("\nWARNING: Field count mismatch!")
                    print(f"Total values: {len(parts_all)} | Expected multiple of {n_fields}")

                records = [
                    parts_all[i:i+n_fields]
                    for i in range(0, len(parts_all), n_fields)
                ]

                parts = records[0]

            if len(parts) < n_fields:
                parts += [None] * (n_fields - len(parts))

            parts = parts[:n_fields]

            # Debug print
            print("\nValue check:")
            print("Raw value:", value[:200], "...")

            for i, (header, val) in enumerate(zip(subfields, parts)):
                print(f"  {i:02d} | {header:35} -> {val}")

            return parts

        expanded = df[field].apply(split_first_record).apply(pd.Series)

        expanded.columns = [f"{field}_{c}" for c in subfields]

        print("\nExpanded column names:")
        for c in expanded.columns:
            print(" ", c)

        df = df.drop(columns=[field])
        df = pd.concat([df, expanded], axis=1)

    return df


# === Step 3: Calculate End_Position ===
def calculate_end_position(df):

    def compute_end(row):

        id_val = row.get("ID", "")
        ref = row.get("REF", "") or ""
        alt = row.get("ALT", "") or ""
        dupsvlen = row.get("DUPSVLEN", "")

        try:
            start = int(row["Start_Position"])
        except (ValueError, TypeError, KeyError):
            return None

        if id_val == ".":
            if len(ref) == len(alt):
                return start
            return start + max(len(ref), len(alt)) - 1

        if str(id_val).startswith("MantaBND"):
            return None

        if str(id_val).startswith("MantaINS"):
            if alt == "<INS>":
                try:
                    return start + int(dupsvlen)
                except (ValueError, TypeError):
                    return None
            return start + len(alt)

        if str(id_val).startswith("MantaDUP"):
            try:
                return start + int(dupsvlen)
            except (ValueError, TypeError):
                return None

        return None

    df["End_Position"] = df.apply(compute_end, axis=1)

    return df


# === Step 4: Clean values ===
def clean_column_values(df):

    df = df.replace({"[]": "", "%3D": "="}, regex=False)

    if "HGVSc" in df.columns:
        df["HGVSc"] = (
            df["HGVSc"]
            .astype(str)
            .apply(lambda x: x.split(":", 1)[1] if ":" in x else x)
        )

    return df


# === Step 5: Compute VAF ===
def add_vaf_column(df, ad_column="AD"):

    if ad_column not in df.columns:
        return df

    def compute_vaf(value):

        try:
            ref, alt = str(value).split(",")
            ref = float(ref)
            alt = float(alt)
            total = ref + alt
            return alt / total if total > 0 else 0
        except Exception:
            return None

    df["VAF"] = df[ad_column].apply(compute_vaf)

    return df


# === Step 6: Drop columns ===
def drop_columns(df, cols_to_remove):

    return df.drop(columns=cols_to_remove, errors="ignore")


# === Step 7: Report undocumented columns ===
def report_undocumented_columns(df, field_config, field_patterns):

    undocumented = []

    for col in sorted(df.columns):
        meta = resolve_field_meta(col, field_config, field_patterns)
        if not meta:
            undocumented.append(col)

    if undocumented:
        print("\n=== WARNING: Undocumented columns found ===")
        for col in undocumented:
            print(f"Undocumented column: {col}")


# === Step 8: Build two-row header ===
def build_multiindex_header(df, field_config, field_patterns):

    metadata_row = []

    for col in df.columns:

        meta = resolve_field_meta(col, field_config, field_patterns)

        description = meta.get("description", "UNKNOWN")
        source      = meta.get("source", "UNKNOWN")
        version     = meta.get("version", "UNKNOWN")

        metadata_row.append(f"{description} | {source} | {version}")

    df.columns = pd.MultiIndex.from_arrays(
        [df.columns, metadata_row],
        names=["Field", "Metadata"]
    )

    return df


# === Step 9: Split dataframe by tier ===
# Tier assignments are read from Config.yaml (set by build_config.py).
# Tier 2 columns : fields with tier == 2 in the YAML
# Tier 3 columns : fields with tier == 3 in the YAML
# All other non-drop columns default to Tier 1 (present in the MAF only)
def split_by_tier(df, field_config, field_patterns):

    tier2_cols = []
    tier3_cols = []
    drop_cols  = []

    for col in df.columns:

        meta = resolve_field_meta(col, field_config, field_patterns)
        tier = meta.get("tier")

        if tier == "drop":
            drop_cols.append(col)

        elif tier == 2:
            tier2_cols.append(col)

        elif tier == 3:
            tier3_cols.append(col)
            tier2_cols.append(col)

        # tier == 1 or unassigned: present in MAF only, not in TSV outputs

    print(f"\nTier2 columns: {len(tier2_cols)}")
    print(f"Tier3 columns: {len(tier3_cols)}")
    print(f"Dropped columns: {len(drop_cols)}")

    return df[tier2_cols], df[tier3_cols]


# === Main merge function ===
def merge_maf_files(input_dir, output_dir, yaml_config):

    field_config, field_patterns = load_field_config(yaml_config)

    maf_files = [f for f in os.listdir(input_dir) if f.lower().endswith(".maf")]

    if not maf_files:
        raise ValueError("No MAF files found in the directory.")

    dfs = []

    for maf in maf_files:

        path = os.path.join(input_dir, maf)

        print(f"Reading: {path}")

        df = pd.read_csv(path, sep="\t", dtype=str)

        df = standardize_format_column(df)

        dfs.append(df)

    merged = pd.concat(dfs, axis=0, ignore_index=True, sort=False)

    merged = calculate_end_position(merged)
    merged = normalize_format_fields(merged)
    merged = expand_structured_columns(merged, field_config)
    merged = clean_column_values(merged)
    merged = add_vaf_column(merged)
    merged = drop_columns(merged, COLS_TO_REMOVE)

    report_undocumented_columns(merged, field_config, field_patterns)

    # --------------------------------------------------------
    # Remove all columns marked as "drop" in the YAML config.
    # These are redundant or duplicate fields and are excluded
    # from every output file without exception.
    # --------------------------------------------------------
    drop_cols = [
        col for col in merged.columns
        if resolve_field_meta(col, field_config, field_patterns).get("tier") == "drop"
    ]

    merged = merged.drop(columns=drop_cols, errors="ignore")

    os.makedirs(output_dir, exist_ok=True)

    tier1_maf  = os.path.join(output_dir, "Final_result_tier1.maf")
    tier2_file = os.path.join(output_dir, "Final_result_tier2.tsv")
    tier3_file = os.path.join(output_dir, "Final_result_tier3.tsv")

    # --------------------------------------------------------
    # Tier 1 MAF: all remaining non-drop columns, single header.
    # Standard MAF format — no metadata second row.
    # --------------------------------------------------------
    print(f"\nWriting Tier1 MAF (all non-drop columns, no metadata header): {tier1_maf}")
    merged.to_csv(tier1_maf, sep="\t", index=False)

    # --------------------------------------------------------
    # Split into Tier 2 and Tier 3 subsets.
    # Tier assignments come from Config.yaml — to change which
    # fields appear in each file, edit build_config.py and
    # re-run it to regenerate Config.yaml.
    # --------------------------------------------------------
    tier2_df, tier3_df = split_by_tier(merged, field_config, field_patterns)

    # --------------------------------------------------------
    # Tier 2 TSV: bioinformatician fields, two-row header.
    # --------------------------------------------------------
    tier2_df = build_multiindex_header(tier2_df, field_config, field_patterns)

    print(f"Writing Tier2 TSV (bioinformaticians, two-row header): {tier2_file}")
    tier2_df.to_csv(tier2_file, sep="\t", index=False)

    # --------------------------------------------------------
    # Tier 3 TSV: clinical scientist fields, two-row header.
    # --------------------------------------------------------
    if tier3_df.empty or len(tier3_df.columns) == 0:
        print("\nWARNING: No Tier 3 columns found in data.")
        print("To populate Final_result_tier3.tsv, add fields to TIER3_FIELDS")
        print("in build_config.py and re-run it to regenerate Config.yaml.")
    else:
        tier3_df = build_multiindex_header(tier3_df, field_config, field_patterns)
        print(f"Writing Tier3 TSV (clinical scientists, two-row header): {tier3_file}")
        tier3_df.to_csv(tier3_file, sep="\t", index=False)


# === Entry point ===
if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, help="Path to Config.yaml")
    args = parser.parse_args()

    merge_maf_files(
        input_dir="./FINAL_Table/",
        output_dir="./output/",
        yaml_config=args.config
    )